/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billprint;

/**
 *
 * @author LENOVO
 */
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.event.*;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Billprint extends javax.swing.JFrame {

    /**
     * Creates new form Billprint
     */
    private static float totprice=0;
    public Billprint() {
        initComponents();
        showDate1();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pricefield = new javax.swing.JTextField();
        quanfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        instrufield = new javax.swing.JTextField();
        resetbut = new javax.swing.JButton();
        printbut = new javax.swing.JButton();
        receiptbut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rtrnfield = new javax.swing.JTextField();
        tenderfield = new javax.swing.JTextField();
        addbut = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pricefield1 = new javax.swing.JTextField();
        pricefield2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 140, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clear Vision Optical");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        datlabel.setForeground(new java.awt.Color(255, 255, 255));
        datlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(datlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(datlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(47, 79, 79));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Item Price:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantity:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Product:");

        pricefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pricefieldKeyPressed(evt);
            }
        });

        quanfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quanfieldKeyPressed(evt);
            }
        });

        namefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namefieldKeyPressed(evt);
            }
        });

        instrufield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                instrufieldKeyPressed(evt);
            }
        });

        resetbut.setBackground(new java.awt.Color(0, 153, 153));
        resetbut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetbut.setText("Reset");
        resetbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbutActionPerformed(evt);
            }
        });

        printbut.setBackground(new java.awt.Color(0, 153, 153));
        printbut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printbut.setText("Print");
        printbut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                printbutFocusGained(evt);
            }
        });
        printbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbutActionPerformed(evt);
            }
        });

        receiptbut.setBackground(new java.awt.Color(0, 153, 153));
        receiptbut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        receiptbut.setText("Receipt");
        receiptbut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                receiptbutFocusGained(evt);
            }
        });
        receiptbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptbutActionPerformed(evt);
            }
        });
        receiptbut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                receiptbutKeyPressed(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        area.setMaximumSize(new java.awt.Dimension(50, 50));
        jScrollPane1.setViewportView(area);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Return:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tender:");

        tenderfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tenderfieldFocusLost(evt);
            }
        });
        tenderfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tenderfieldKeyPressed(evt);
            }
        });

        addbut.setBackground(new java.awt.Color(0, 153, 153));
        addbut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addbut.setText("Add item");
        addbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbutActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total Price:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sub Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(resetbut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(receiptbut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printbut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addbut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(instrufield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quanfield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pricefield2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenderfield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rtrnfield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namefield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instrufield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quanfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pricefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pricefield2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addbut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pricefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tenderfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtrnfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptbut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printbut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pricefieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricefieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tenderfield.requestFocus();
            float quan = Float.parseFloat(quanfield.getText());
            float price = Float.parseFloat(pricefield.getText());
            float subtot = quan * price;
            totprice = totprice + subtot;
            pricefield2.setText(String.valueOf(subtot));
            pricefield1.setText(String.valueOf(totprice));
        }
    }//GEN-LAST:event_pricefieldKeyPressed

    private void quanfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quanfieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            pricefield.requestFocus();
        }
    }//GEN-LAST:event_quanfieldKeyPressed

    private void namefieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namefieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            instrufield.requestFocus();
        }
    }//GEN-LAST:event_namefieldKeyPressed

    private void instrufieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instrufieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            quanfield.requestFocus();
        }
    }//GEN-LAST:event_instrufieldKeyPressed

    private void resetbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbutActionPerformed
        pricefield.setText(null);
        pricefield1.setText(null);
        pricefield2.setText(null);
        quanfield.setText(null);
        namefield.setText(null);
        instrufield.setText(null);
        rtrnfield.setText(null);
        tenderfield.setText(null);
        area.setText(null);
        totprice=0;
        namefield.requestFocus();
        Color newc = new Color(0,153,153);
        printbut.setBackground(newc);
        
    }//GEN-LAST:event_resetbutActionPerformed

    private void printbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbutActionPerformed
        System.out.println("Clear Vision Optical");
        try {
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Billprint.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_printbutActionPerformed

    private void receiptbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptbutActionPerformed
        if(area.getText().trim().length() == 0){
            String name = namefield.getText();
            String instru = instrufield.getText();
            String quan = quanfield.getText();
            String price = pricefield2.getText();
            String dat = datlabel.getText();
            area.setText("\tClear Vision Optical\n   "+ "\t   Itahari,Sunsari\n\n");
            area.append(dat);
            area.append("\n-----------------");
            area.append("\nName: "+name);
            area.append("\n\nProduct\t  Quantity\t  Price\n");
            area.append("------------------------------------------------------\n");
            area.append(instru+"\t  "+quan+"\t  "+price);
        }
        else{
            String instru = instrufield.getText();
            String quan = quanfield.getText();
            String price = pricefield2.getText();
            area.append("\n"+instru+"\t  "+quan+"\t  "+price);
        }
        area.append("\n------------------------------------------------------\n");
        area.append("     Total\t\t"+totprice);
        area.append("\n\tThank you! Visit Again");
        printbut.requestFocus(); 
        Color newc = new Color(0,153,153);
        receiptbut.setBackground(newc);
    }//GEN-LAST:event_receiptbutActionPerformed

    private void tenderfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tenderfieldFocusLost
        float price = Float.parseFloat(pricefield1.getText());
        float tender = Float.parseFloat(tenderfield.getText());
        float retrn = tender-price;
        rtrnfield.setText(String.valueOf(retrn));
    }//GEN-LAST:event_tenderfieldFocusLost

    private void tenderfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenderfieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            float price = Float.parseFloat(pricefield1.getText());
            float tender = Float.parseFloat(tenderfield.getText());
            float retrn = tender-price;
            rtrnfield.setText(String.valueOf(retrn));
            receiptbut.requestFocus();
        }
    }//GEN-LAST:event_tenderfieldKeyPressed

    private void addbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbutActionPerformed
        if(namefield.getText().equals("") || instrufield.getText().equals("")){
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f,"Add item first");
        }
        else{
        if(area.getText().trim().length() == 0){
            String name = namefield.getText();
            String instru = instrufield.getText();
            String quan = quanfield.getText();
            String price = pricefield1.getText();
            String dat = datlabel.getText();
            area.setText("\tClear Vision Optical\n   "+ "\t   Itahari,Sunsari\n\n");
            area.append(dat);
            area.append("\n-----------------");
            area.append("\nName: "+name);
            area.append("\n\nProduct\t  Quantity\t  Price\n");
            area.append("------------------------------------------------------\n");
            area.append(instru+"\t  "+quan+"\t  "+price);
        }
        else{
            String instru = instrufield.getText();
            String quan = quanfield.getText();
            String price = pricefield1.getText();
            area.append("\n"+instru+"\t"+quan+"\t"+price);
        }
        pricefield.setText(null);
        pricefield2.setText(null);
        quanfield.setText(null);
        instrufield.setText(null);
        rtrnfield.setText(null);
        tenderfield.setText(null);
        instrufield.requestFocus();
        }
    }//GEN-LAST:event_addbutActionPerformed

    private void receiptbutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiptbutKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(area.getText().trim().length() == 0){
            String name = namefield.getText();
            String instru = instrufield.getText();
            String quan = quanfield.getText();
            String price = pricefield1.getText();
            String dat = datlabel.getText();
            area.setText("\tClear Vision Optical\n   "+ "\t   Itahari,Sunsari\n\n");
            area.append(dat);
            area.append("\n-----------------");
            area.append("\nName: "+name);
            area.append("\n\nProduct\t  Quantity\t  Price\n");
            area.append("------------------------------------------------------\n");
            area.append(instru+"\t  "+quan+"\t  "+price);
        }
        else{
            String instru = instrufield.getText();
            String quan = quanfield.getText();
            String price = pricefield1.getText();
            area.append("\n"+instru+"\t  "+quan+"\t "+price);
        }
           area.append("\n------------------------------------------------------\n");
           area.append("     Total\t\t"+totprice);
           area.append("\n\tThank you! Visit Again");
           printbut.requestFocus(); 
           Color newc = new Color(0,153,153);
           receiptbut.setBackground(newc);
        }
    }//GEN-LAST:event_receiptbutKeyPressed

    private void receiptbutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_receiptbutFocusGained
        receiptbut.setBackground(Color.YELLOW);
    }//GEN-LAST:event_receiptbutFocusGained

    private void printbutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_printbutFocusGained
       printbut.setBackground(Color.YELLOW);
    }//GEN-LAST:event_printbutFocusGained

    /**
     * @param args the command line arguments
     */
    void showDate1(){
        Date date = new Date();
        SimpleDateFormat datefor = new SimpleDateFormat("yyyy-MM-dd");
        datlabel.setText(datefor.format(date));
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billprint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbut;
    private javax.swing.JTextArea area;
    private javax.swing.JLabel datlabel;
    private javax.swing.JTextField instrufield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField pricefield;
    private javax.swing.JTextField pricefield1;
    private javax.swing.JTextField pricefield2;
    private javax.swing.JButton printbut;
    private javax.swing.JTextField quanfield;
    private javax.swing.JButton receiptbut;
    private javax.swing.JButton resetbut;
    private javax.swing.JTextField rtrnfield;
    private javax.swing.JTextField tenderfield;
    // End of variables declaration//GEN-END:variables
}
